<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/config.php';
require_once __DIR__ . '/../app/helpers.php';
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/RiskAnalyzer.php';
require_once __DIR__ . '/../app/assessment.php';
require_once __DIR__ . '/../app/susceptibility.php';
require_once __DIR__ . '/../app/awareness.php';
require_once __DIR__ . '/../app/presentation.php';
require_once __DIR__ . '/../app/repositories.php';
require_once __DIR__ . '/../app/maintenance.php';
require_once __DIR__ . '/../app/csv.php';
require_once __DIR__ . '/../app/weather.php';
if (!str_ends_with($config['db_name'],'_test')) throw new RuntimeException('Use a disposable *_test database.');
$pdo=db();
$checks=0;
function integration_check(bool $ok, string $message): void { global $checks; if (!$ok) throw new RuntimeException($message); $checks++; }
$location=get_locations()[0];
$user=create_user('Test Resident','testresident','resident@test.invalid','+639000000001','testpass123');
$base=['location_id'=>$location['id'],'rainfall_1h'=>12,'rainfall_24h'=>60,'rainfall_72h'=>90,'risk_level'=>'medium',
'observed_at'=>gmdate('Y-m-d H:i:s'),'rainfall_window_end'=>gmdate('Y-m-d H:00:00'),'source'=>'manual','rule_version'=>RiskAnalyzer::VERSION,'provider_payload'=>json_encode(['classification'=>'TEST/DEMO','hourly'=>[12,48,30]])];
$id=create_reading($base); $repeat=create_reading($base);
$row=get_latest_reading((int)$location['id']);
integration_check((int)$row['id']===$repeat,'Latest snapshot ordered by id when provider time repeats.');
integration_check(json_decode($row['provider_payload'],true)['classification']==='TEST/DEMO','Input JSON persisted.');
update_reading_risk($repeat,'high',1,'TEST/DEMO administrator review');
$row=get_latest_reading((int)$location['id']);
integration_check($row['assessment']['adjusted'] && $row['assessment']['calculated_category']==='medium','Stored administrator category stays separate.');
update_reading_risk($repeat,'medium',1,'TEST/DEMO return to calculated category');
$row=get_latest_reading((int)$location['id']);
$log=json_decode($row['adjustment_log'],true);
integration_check(count($log)===2 && $log[0]['from']==='medium' && $log[1]['to']==='medium','Both risk edits retained.');
integration_check($row['assessment']['adjusted'],'Edit matching calculated category still identified.');
$report=create_report(['location_id'=>$location['id'],'user_id'=>$user,'message'=>'TEST/DEMO report','contact_phone'=>'+639000000001','house_landmark'=>'TEST/DEMO','report_type'=>'ground_cracks','occurred_at'=>report_occurrence('2026-01-01T08:00')]);
update_report($report,'reviewed',1);
$r=get_reports('reviewed')[0];
integration_check((int)$r['user_id']===$user && (int)$r['reviewed_by']===1 && $r['reviewed_at']!==null,'Report review preserves submitter and records reviewer/time.');
integration_check($r['report_type']==='ground_cracks' && $r['occurred_at']==='2026-01-01 00:00:00','Structured fields persisted UTC.');
integration_check(location_report_summary((int)$location['id'])['reviewed']===1,'Location summary grouped by workflow state.');
$csv=export_readings_csv(get_all_readings());
integration_check(str_contains($csv,'Data source') && str_contains($csv,'administrator review'),'CSV retains source and audit metadata.');
integration_check(archive_reading($id),'Archive original reading.');
$bad=$base; $bad['rainfall_24h']=10; create_reading($bad);
integration_check(get_latest_reading((int)$location['id'])['assessment']['current_category']===null,'Invalid saved windows unavailable.');
integration_check(!update_report($report,'reviewed',1),'Repeated review reports no change.');
$export=export_locations_csv(get_locations());
$import=parse_locations_csv($export);
integration_check(import_locations_csv($import)['unchanged']===count($import),'Unchanged location import is idempotent.');
deactivate_location((int)$location['id']);
integration_check(import_locations_csv($import)['updated']===1,'Import restores inactive location.');
integration_check((int)get_location((int)$location['id'])['active']===1,'Restored location retains original ID.');
integration_check((int)$pdo->query('SELECT location_id FROM events WHERE id='.(int)$report)->fetchColumn()===(int)$location['id'],'Import preserves report history links.');
$pdo->prepare('DELETE FROM events WHERE location_id=?')->execute([$location['id']]);
echo "$checks database integration checks passed.\n";
